VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # See also https://atlas.hashicorp.com/debian/

  config.vm.box = "debian/jessie64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "dockerhost.test" do |machine|
    #machine.vm.network "private_network", ip: "10.10.10.110"
    machine.vm.network "public_network", ip: "10.10.10.110"
  end
end


